export const environment = {
  DATABASE_URL: process.env.DATABASE_URL!,

  SENDGRID_API_KEY: process.env.SENDGRID_API_KEY!,
  SENDGRID_SENDER: process.env.SENDGRID_SENDER!,
  SENDGRID_FORGOT_PASSWORD_TEMPLATE: process.env.SENDGRID_FORGOT_PASSWORD_TEMPLATE!,
  SENDGRID_VERIFY_ACCOUNT_TEMPLATE: process.env.SENDGRID_VERIFY_ACCOUNT_TEMPLATE!,

  JWT_FORGOT_PASSWORD_SECRET: process.env.JWT_FORGOT_PASSWORD_SECRET!,
  JWT_VERIFY_ACCOUNT_SECRET: process.env.JWT_VERIFY_ACCOUNT_SECRET!,
  JWT_SECRET: process.env.JWT_SECRET!,
  
  DOMAIN_URL: process.env.DOMAIN_URL!,

  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID!,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET!
}